# Generated by Django 6.0.3 on 2026-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
